### ISSUE TITLE
Logo design for sharemusic

### ISSUE THREAD

**Issue by zuurw** [pando85/sharemusic#2]
Hi , my name is Zuur W. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by remipassmoilesel** [comment]
Hi, this project is a small toolbox for nerds, I don't if it need a fancy logo :)

**Comment by AgilDat** [comment]
Haha
That's correct but if you want to propose one new icon/logo your help is welcome. I'm very bad with designs and graphics. Thanks!

**Comment by pando85** [comment]
Haha
That's correct but if you want to propose one new icon/logo your help is welcome. I'm very bad with designs and graphics. Thanks!

**Comment by remipassmoilesel** [comment]
Sorry @pando85, I've got the same issue on my "small toolbox for nerds", so I've answered on the wrong repo, yours. No offense ;D

https://github.com/remipassmoilesel/linux-utils/issues/1

**Comment by pando85** [comment]
No offense, this is similar xD I think I'm the unique user of this repo. Your message make me laugh :)

**Comment by zuurw** [comment]
Hi @pando85, do you have any special request for the logo? can you give me something for get inspired?

Best regards!

**Comment by pando85** [comment]
This is an application to share music between people so logo must be related with cloud and music. Basically, it's a web server to play your music.

**Comment by zuurw** [comment]
Hi @pando85, here is my design for Sharemusic, for the concept I get inspired in cloud, music and share, so I create a cloud with circles the big circle has a player button as a reference to music and finally I create little circles that represente people that are sharing music.

I create 4 versions of the logo and one color, two colors and black version too, also I choose two different typeface for the logo with one color and two colors version.

I hope you like it, if not I can make another one or make some changes.

Best Regards!

![proposal](https://user-images.githubusercontent.com/40801473/43905498-1ce9cd80-9be9-11e8-8b03-3f77dd941a46.png)

**Comment by pando85** [comment]
Omg Ty Very much, this is very cool. I will add it to the app. Thanks!

**Comment by pando85** [comment]
Where could I get the images?

**Comment by zuurw** [comment]
I will submit a PR with png files and also with SVG and EPS (editable format), wich one do you want and color for the main logo? and wich typeface do you want?

Best Regards!

**Comment by pando85** [comment]
My favourite is #4 in two colours. And my best typeface is top-rigth. I usually use it with black background too so I will make one with colours inverted (example: [login page](https://music.grigri.cloud)) and I think model #1 could be better for web icon. Thanks for all

**Comment by zuurw** [comment]
Hi @pando85, I submitted the PR with the logo files, icons and update the README file adding the logotype there.

Best Regards!

**Comment by pando85** [comment]
PR: #3 
Thanks!
